/*
 * This file was automatically generated by EvoSuite
 * Thu Apr 21 13:29:41 GMT 2022
 */


import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true) 
public class AesEaxJce_ESTest extends AesEaxJce_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      byte[] byteArray0 = new byte[18];
      byteArray0[3] = (byte)125;
      byte[] byteArray1 = AesEaxJce.multiplyByX_unsafe(byteArray0);
      assertEquals(16, byteArray1.length);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      byte[] byteArray0 = new byte[9];
      byte[] byteArray1 = AesEaxJce.multiplyByX_exp_unsafe(byteArray0, (-1974));
      assertNull(byteArray1);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      // Undeclared exception!
      try { 
        AesEaxJce.multiplyByX_unsafe((byte[]) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      // Undeclared exception!
      try { 
        AesEaxJce.multiplyByX_unsafe(byteArray0);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      // Undeclared exception!
      try { 
        AesEaxJce.multiplyByX_exp_unsafe((byte[]) null, 588);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      // Undeclared exception!
      try { 
        AesEaxJce.multiplyByX_exp_unsafe(byteArray0, (byte)1);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      byte[] byteArray0 = new byte[18];
      byteArray0[0] = (byte)119;
      byte[] byteArray1 = AesEaxJce.multiplyByX_unsafe(byteArray0);
      byte[] byteArray2 = AesEaxJce.multiplyByX_unsafe(byteArray1);
      assertEquals(16, byteArray2.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      byte[] byteArray0 = new byte[18];
      byteArray0[0] = (byte)119;
      byte[] byteArray1 = AesEaxJce.multiplyByX_unsafe(byteArray0);
      byte[] byteArray2 = AesEaxJce.multiplyByX_exp_unsafe(byteArray1, (byte)119);
      byte[] byteArray3 = AesEaxJce.multiplyByX_exp_unsafe(byteArray2, 15);
      assertEquals(16, byteArray3.length);
      assertNotNull(byteArray3);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      byte[] byteArray0 = new byte[25];
      // Undeclared exception!
      AesEaxJce.multiplyByX_exp_unsafe(byteArray0, 2584);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      AesEaxJce aesEaxJce0 = new AesEaxJce();
  }
}
